/* Distribution of the teaching faculty by gender and department */

WITH GENDER_TALLY AS (
    SELECT T.DEPARTMENT AS "ID", 
           D.NAME AS "DEPARTMENT", 
           SUM(CASE WHEN T.GENDER = 'M' THEN 1 ELSE 0 END) AS "MALES", 
           SUM(CASE WHEN T.GENDER = 'F' THEN 1 ELSE 0 END) AS "FEMALES", 
           COUNT(*) AS "TOTAL"
    FROM TEACHERS_SM T
    INNER JOIN DEPARTMENTS_SM D ON D.DEPARTMENT_ID = T.DEPARTMENT
    GROUP BY T.DEPARTMENT, D.NAME
    ORDER BY "ID" ASC
), OVERALL_DISTRIBUTION AS (
    SELECT 'OVERALL' AS "DEPARTMENT",
           SUM(MALES) AS "TOTAL_MALES",
           SUM(FEMALES) AS "TOTAL_FEMALES",
           SUM(TOTAL) AS "TOTAL"
    FROM GENDER_TALLY
)
SELECT DEPARTMENT, 
       ROUND((MALES/TOTAL)*100, 1) AS "% MALE",
       ROUND((FEMALES/TOTAL)*100, 1) AS "% FEMALE"
FROM GENDER_TALLY
UNION ALL
SELECT DEPARTMENT, 
       ROUND((TOTAL_MALES/TOTAL)*100, 1) AS "% MALE",
       ROUND((TOTAL_FEMALES/TOTAL)*100, 1) AS "% FEMALE" 
FROM OVERALL_DISTRIBUTION;